# Generated by Django 6.1.1 on 2026-09-30 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DNI', 'DNI'), ('CUD', 'Certificado Único de Discapacidad'), ('ORDEN_MEDICA', 'Orden médica'), ('ESTUDIO', 'Estudio'), ('CERTIFICADO', 'Certificado'), ('CONSENTIMIENTO', 'Consentimiento'), ('OTRO', 'Otro')], default='OTRO', max_length=30)),
                ('nombre', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to='documentos/%Y/%m/')),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_documento', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='personas.persona')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
