# Generated by Django 6.1.1 on 2026-09-30 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObraSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('codigo', models.CharField(blank=True, max_length=80)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=150)),
                ('cuit', models.CharField(blank=True, max_length=20, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Obra social',
                'verbose_name_plural': 'Obras sociales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoDiagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de diagnóstico',
                'verbose_name_plural': 'Tipos de diagnóstico',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historia_clinica', models.CharField(blank=True, max_length=80, unique=True)),
                ('numero_cud', models.CharField(blank=True, max_length=100)),
                ('fecha_vencimiento_cud', models.DateField(blank=True, null=True)),
                ('nro_afiliado', models.CharField(blank=True, max_length=100)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('obra_social', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pacientes', to='pacientes.obrasocial')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='paciente', to='personas.persona')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['persona__apellido', 'persona__nombre'],
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('codigo_cie10', models.CharField(blank=True, max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnosticos', to='pacientes.tipodiagnostico')),
            ],
            options={
                'verbose_name': 'Diagnóstico',
                'verbose_name_plural': 'Diagnósticos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PacienteDiagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('REAL', 'Real'), ('CUD', 'CUD')], default='REAL', max_length=10)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pacientes', to='pacientes.diagnostico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnosticos', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Diagnóstico del paciente',
                'verbose_name_plural': 'Diagnósticos de pacientes',
                'constraints': [models.UniqueConstraint(fields=('paciente', 'diagnostico', 'tipo'), name='unique_paciente_diagnostico_tipo')],
            },
        ),
        migrations.CreateModel(
            name='ResponsablePaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(blank=True, max_length=80)),
                ('es_principal', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsables', to='pacientes.paciente')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pacientes_a_cargo', to='personas.persona')),
            ],
            options={
                'verbose_name': 'Responsable del paciente',
                'verbose_name_plural': 'Responsables de pacientes',
                'constraints': [models.UniqueConstraint(fields=('paciente', 'persona'), name='unique_responsable_paciente')],
            },
        ),
        migrations.AddConstraint(
            model_name='diagnostico',
            constraint=models.UniqueConstraint(fields=('tipo', 'nombre'), name='unique_diagnostico_tipo'),
        ),
    ]
