# Generated by Django 6.1.1 on 2026-09-30 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de servicio',
                'verbose_name_plural': 'Tipos de servicio',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_base', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('duracion_minutos', models.PositiveIntegerField(default=60)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('tipo_servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='servicios.tiposervicio')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProfesionalServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios_profesionales', to='empleados.empleado')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profesionales', to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Servicio del profesional',
                'verbose_name_plural': 'Servicios de profesionales',
                'constraints': [models.UniqueConstraint(fields=('empleado', 'servicio'), name='unique_profesional_servicio')],
            },
        ),
        migrations.CreateModel(
            name='ServicioObraSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_autorizado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('codigo_obra_social', models.CharField(blank=True, max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('obra_social', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='pacientes.obrasocial')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obras_sociales', to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Servicio por obra social',
                'verbose_name_plural': 'Servicios por obras sociales',
                'constraints': [models.UniqueConstraint(fields=('servicio', 'obra_social'), name='unique_servicio_obra_social')],
            },
        ),
        migrations.AddConstraint(
            model_name='servicio',
            constraint=models.UniqueConstraint(fields=('tipo_servicio', 'nombre'), name='unique_servicio_tipo'),
        ),
    ]
