# Generated by Django 6.1.1 on 2026-09-30 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(blank=True, max_length=50)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('horas_semanales', models.PositiveIntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='empleado', to='personas.persona')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['persona__apellido', 'persona__nombre'],
            },
        ),
        migrations.CreateModel(
            name='AsistenciaEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_entrada', models.TimeField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='empleados.empleado')),
            ],
            options={
                'verbose_name': 'Asistencia del empleado',
                'verbose_name_plural': 'Asistencias de empleados',
                'ordering': ['-fecha'],
                'constraints': [models.UniqueConstraint(fields=('empleado', 'fecha'), name='unique_asistencia_empleado_fecha')],
            },
        ),
        migrations.CreateModel(
            name='HorarioEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIERCOLES', 'Miércoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes'), ('SABADO', 'Sábado')], max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horarios', to='empleados.empleado')),
            ],
            options={
                'verbose_name': 'Horario del empleado',
                'verbose_name_plural': 'Horarios de empleados',
                'ordering': ['empleado', 'dia_semana', 'hora_inicio'],
                'constraints': [models.UniqueConstraint(fields=('empleado', 'dia_semana', 'hora_inicio', 'hora_fin'), name='unique_horario_empleado')],
            },
        ),
        migrations.CreateModel(
            name='EmpleadoRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roles', to='empleados.empleado')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='empleados.rol')),
            ],
            options={
                'verbose_name': 'Rol del empleado',
                'verbose_name_plural': 'Roles de empleados',
                'constraints': [models.UniqueConstraint(fields=('empleado', 'rol'), name='unique_empleado_rol')],
            },
        ),
    ]
