# Generated by Django 6.1.1 on 2026-09-30 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
        ('pacientes', '0001_initial'),
        ('servicios', '0001_initial'),
        ('tratamientos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('REALIZADO', 'Realizado'), ('CANCELADO', 'Cancelado'), ('AUSENTE', 'Ausente')], default='PENDIENTE', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='pacientes.paciente')),
                ('plan_tratamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='tratamientos.plantratamiento')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='empleados.empleado')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['-fecha', '-hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='AsistenciaPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('presente', models.BooleanField(default=True)),
                ('hora_llegada', models.TimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('turno', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='asistencia', to='turnos.turno')),
            ],
            options={
                'verbose_name': 'Asistencia del paciente',
                'verbose_name_plural': 'Asistencias de pacientes',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.AddConstraint(
            model_name='turno',
            constraint=models.UniqueConstraint(fields=('profesional', 'fecha', 'hora_inicio'), name='unique_turno_profesional_fecha_hora'),
        ),
    ]
